export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_TOPPINGS_CATEGORIES = 'SET_TOPPINGS_CATEGORIES';
export const SET_TOPPINGS = 'SET_TOPPINGS';
export const SET_SIZES = 'SET_SIZES';
export const SET_FREE_TOPPINGS_AMOUNT = 'SET_FREE_TOPPINGS_AMOUNT';
export const SET_SELECTED_SIZE = 'SET_SELECTED_SIZE';
export const ADD_TOPPING = 'ADD_TOPPING';
export const REMOVE_TOPPING = 'REMOVE_TOPPING';
export const UPDATE_TOPPINGS_AMOUNT = 'UPDATE_TOPPINGS_AMOUNT';
export const UPDATE_PRICE_ADD = 'UPDATE_PRICE_ADD';
export const UPDATE_PRICE_REMOVE = 'UPDATE_PRICE_REMOVE';
export const SET_TOPPINGS_FOR_CATEGORIES = 'SET_TOPPINGS_FOR_CATEGORIES';
export const SET_LOADING_FOR_CATEGORIES = 'SET_LOADING_FOR_CATEGORIES';
export const SET_LOADING_FOR_CATEGORIES_TOPPINGS =
  'SET_LOADING_FOR_CATEGORIES_TOPPINGS';
export const INIT_PRODUCT_BUILDER = 'INIT_PRODUCT_BUILDER';
export const SET_TOPPINGS_AMOUNT = 'SET_TOPPINGS_AMOUNT';
export const SET_TOPPINGS_PRICE = 'SET_TOPPINGS_PRICE';
export const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR';
export const SET_SIZES_ERROR = 'SET_SIZES_ERROR';
export const SET_CATEGORIES_TOPPINGS_ERROR = 'SET_CATEGORIES_TOPPINGS_ERROR';
export const SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR';
export const SET_CATEGORY_ERROR = 'SET_CATEGORY_ERROR';

